# Form implementation generated from reading ui file 'recipe_ui.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_RecipeWindow(object):
    def setupUi(self, RecipeWindow):
        RecipeWindow.setObjectName("RecipeWindow")
        RecipeWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=RecipeWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.listWidget = QtWidgets.QListWidget(parent=self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(80, 20, 531, 192))
        self.listWidget.setStyleSheet("border-radius: 20px;")
        self.listWidget.setObjectName("listWidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 250, 241, 21))
        self.label.setStyleSheet("font-size: 24px;\n"
"font-weight: bold;")
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(80, 280, 331, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(80, 320, 241, 21))
        self.label_2.setStyleSheet("font-size: 24px;\n"
"font-weight: bold;")
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(80, 350, 331, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        RecipeWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=RecipeWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        RecipeWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=RecipeWindow)
        self.statusbar.setObjectName("statusbar")
        RecipeWindow.setStatusBar(self.statusbar)

        self.retranslateUi(RecipeWindow)
        QtCore.QMetaObject.connectSlotsByName(RecipeWindow)

    def retranslateUi(self, RecipeWindow):
        _translate = QtCore.QCoreApplication.translate
        RecipeWindow.setWindowTitle(_translate("RecipeWindow", "MainWindow"))
        self.label.setText(_translate("RecipeWindow", "Название рецепта"))
        self.label_2.setText(_translate("RecipeWindow", "Описание рецепта"))
